return {{[ [[cssFont]] ] = [[font-family: 'JetBrains Mono NL', sans serif;color: white;]],[ [[mainFontSize]] ] = 13,[ [[displays]] ] = {2},[ [[inactiveTab]] ] = [[color: white; background-color: DimGrey;border-width: 0px; margin-right: 2px; margin-bottom: 2px;border-style: solid; border-color: black;border-top-left-radius: 10px;border-top-right-radius: 10px;]],[ [[gaugeFontSize]] ] = 12,[ [[consoleBackgroundColor]] ] = [[<15,15,15>]],[ [[tabFontSize]] ] = 12,[ [[tabGap]] ] = 2,[ [[promptFontSize]] ] = 12,[ [[consoleFont]] ] = [[JetBrains Mono NL]],[ [[containers]] ] = {3},[ [[altFont]] ] = [[Bitstream Vera Sans Mono]],[ [[topCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 2px solid rgba(40,40,40,100%);]],[ [[numberSystem]] ] = [[eu]],[ [[inactiveTabBGColor]] ] = [[DimGrey]],[ [[userToggles]] ] = {4},[ [[activeTabBGColor]] ] = [[DarkOliveGreen]],[ [[tabHeight]] ] = 20,[ [[containerTitleTextColor]] ] = [[black]],[ [[moveableConsoleCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 2px solid rgba(40,40,40,100%);padding-top: 10px;]],[ [[rightCSS]] ] = [[background-color:rgba(15,15,15,100%);]],[ [[activeTabFGColor]] ] = [[white]],[ [[leftCSS]] ] = [[background-color:rgba(15,15,15,100%);border-right: 2px solid rgba(40,40,40,100%);]],[ [[bottomCSS]] ] = [[background-color:rgba(15,15,15,100%);border-top: 2px solid rgba(40,40,40,100%);]],[ [[activeTab]] ] = [[color: white; background-color: DarkOliveGreen;border-width: 0px; margin-right: 2px; margin-bottom: 2px;border-style: solid; border-color: black;border-top-left-radius: 10px;border-top-right-radius: 10px;]],[ [[tabBarColor]] ] = [[<15,15,15>]],[ [[consoleFontSize]] ] = 11,[ [[inactiveTabFGColor]] ] = [[white]],[ [[mainFont]] ] = [[JetBrains Mono NL]],},
{[ [[charDisplay]] ] = {5},[ [[affectsDisplay]] ] = {6},[ [[gaugeDisplay]] ] = {7},[ [[topDisplay]] ] = {8},[ [[roomDisplay]] ] = {9},[ [[promptDisplay]] ] = {10},[ [[eqDisplay]] ] = {11},[ [[promptRightDisplay]] ] = {12},[ [[mapperDisplay]] ] = {13},[ [[channelDisplay]] ] = {14},},
{[ [[container5]] ] = {15},[ [[container1]] ] = {16},[ [[container4]] ] = {17},[ [[container3]] ] = {18},[ [[container10]] ] = {19},[ [[container8]] ] = {20},[ [[container9]] ] = {21},[ [[container7]] ] = {22},[ [[container2]] ] = {23},[ [[container6]] ] = {24},},
{[ [[convinience]] ] = {25},[ [[gagging]] ] = {26},},
{[ [[dest]] ] = [[container1]],[ [[tabs]] ] = {27},[ [[emco]] ] = true,},
{[ [[dest]] ] = [[container8]],[ [[wrap]] ] = true,[ [[tabs]] ] = {28},[ [[emco]] ] = true,},
{[ [[dest]] ] = [[container5]],},
{[ [[dest]] ] = [[container10]],},
{[ [[dest]] ] = [[container3]],[ [[wrap]] ] = true,[ [[tabs]] ] = {29},[ [[emco]] ] = true,},
{[ [[dest]] ] = [[container6]],},
{[ [[dest]] ] = [[container2]],[ [[tabs]] ] = {30},[ [[emco]] ] = true,},
{[ [[dest]] ] = [[container9]],[ [[wrap]] ] = true,},
{[ [[tabs]] ] = {31},[ [[mapTab]] ] = [[Mapper]],[ [[dest]] ] = [[container7]],[ [[mapper]] ] = true,[ [[emco]] ] = true,},
{[ [[tabs]] ] = {32},[ [[dest]] ] = [[container4]],[ [[wrap]] ] = true,[ [[emco]] ] = true,[ [[allTab]] ] = true,},
{[ [[y]] ] = [[-52px]],[ [[customCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 0px solid rgba(15,15,15,100%);padding-top: 10px;]],[ [[dest]] ] = [[bottom]],[ [[height]] ] = [[50px]],[ [[width]] ] = [[530px]],},
{[ [[dest]] ] = [[left]],[ [[y]] ] = 0,[ [[height]] ] = 12,},
{[ [[dest]] ] = [[right]],[ [[y]] ] = 0,[ [[height]] ] = [[50%]],},
{[ [[dest]] ] = [[left]],[ [[height]] ] = 15,[ [[y]] ] = 40,[ [[customCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 0px solid rgba(15,15,15,100%);padding-top: 10px;]],},
{[ [[dest]] ] = [[top]],[ [[height]] ] = 2,[ [[y]] ] = 0,[ [[customCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 0px solid rgba(15,15,15,100%);padding-top: 10px;]],},
{[ [[dest]] ] = [[left]],[ [[y]] ] = 30,[ [[height]] ] = 10,},
{[ [[y]] ] = [[-52px]],[ [[x]] ] = [[540px]],[ [[customCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 0px solid rgba(200,15,15,100%);padding-top: 10px;]],[ [[dest]] ] = [[bottom]],[ [[height]] ] = [[50px]],[ [[width]] ] = [[150px]],},
{[ [[dest]] ] = [[right]],[ [[y]] ] = [[-50%]],[ [[height]] ] = [[50%]],},
{[ [[dest]] ] = [[left]],[ [[y]] ] = 12,[ [[height]] ] = 18,},
{[ [[y]] ] = 0,[ [[customCSS]] ] = [[background-color:rgba(15,15,15,100%);border-bottom: 0px solid rgba(15,15,15,100%);padding-top: 10px;]],[ [[dest]] ] = [[bottom]],[ [[fs]] ] = 12,[ [[height]] ] = 3,},
{[ [[numpadWalking]] ] = {33},},
{[ [[balance]] ] = {34},[ [[prompt]] ] = {35},[ [[blank]] ] = {36},},
{[1] = [[Character]],[2] = [[Wholist]],},
{[1] = [[Affects]],[2] = [[Group]],},
{[1] = [[Room]],[2] = [[Combat]],},
{[1] = [[Equipment]],[2] = [[Inventory]],[3] = [[Pets]],},
{[1] = [[Mapper]],[2] = [[Settings]],},
{[1] = [[All]],[2] = [[Chat]],[3] = [[Tell]],[4] = [[Local]],[5] = [[Misc]],[6] = [[Group]],},
{[ [[state]] ] = true,[ [[desc]] ] = [[Numberpad walking]],},
{[ [[state]] ] = false,[ [[desc]] ] = [[Gag Balance Messages]],},
{[ [[state]] ] = false,[ [[desc]] ] = [[Gag prompt]],},
{[ [[state]] ] = false,[ [[desc]] ] = [[Gag Blank Messages]],},
}