function ui.updateDisplays(args)
  args = args or {}
  ui.updatePromptDisplay()
  ui.updateEQDisplay()
  ui.updateInvDisplay()
  ui.updateRoomDisplay()
  ui.updateEnemyGauge()
  ui.updateBalanceGauge()
  ui.updatePlayerGauges()
  ui.updateChannelDisplay()
  ui.updateCharDisplay()
  ui.updateWhoDisplay()
  ui.updatePromptRightDisplay()
  ui.updateAffectsDisplay()
  ui.updateGroupDisplay()
  ui.updateTopBar()
  ui.updateCombatDisplay()
  ui.resizeEvent()
end