function wui.updateDisplays(args)
  args = args or {}
  wui.updatePromptDisplay()
  wui.updateEQDisplay()
  wui.updateInvDisplay()
  wui.updateRoomDisplay()
  wui.updateEnemyGauge()
  wui.updateBalanceGauge()
  wui.updatePlayerGauges()
  wui.updateChannelDisplay()
  wui.updateCharDisplay()
  wui.updateWhoDisplay()
  wui.updatePromptRightDisplay()
  wui.updateAffectsDisplay()
  wui.updateGroupDisplay()
  wui.updateTopBar()
  wui.updateCombatDisplay()
  wui.resizeEvent()
end